base_url = "https://karamoff.dev"

title = "Nikita Karamov"
description = "A web developer."

default_language = "en-gb"

theme = "lightspeed"

compile_sass = true
minify_html = true
generate_feed = true
build_search_index = false

[markdown]
highlight_code = true
highlight_theme = "OneHalfLight"
external_links_target_blank = false
external_links_no_referrer = true
smart_punctuation = true

[extra]
zola = false
netlify = false
maintained_with_love = false
footer_tagline = "..."
