base_url = "https://www.kytta.dev"

title = "@kytta"
description = "A π-shaped web developer."
author = "Nikita Karamov"

default_language = "en"

compile_sass = true
minify_html = true
generate_feeds = true
feed_filenames = ["atom.xml", "rss.xml"]

[markdown]
highlight_code = true
highlight_theme = "two-dark"

smart_punctuation = true
bottom_footnotes = true

[extra]
menu = [
    { path = "blog/_index.md", type = "section" },
    { title = "Uses", path = "uses.md", type = "page" },
    { path = "donate.md", type = "page" },
    { title = "Contact", path = "contact.md", type = "page" },
]

license = { name = "CC BY-SA 4.0", href = "https://creativecommons.org/licenses/by-sa/4.0/" }
fediverse_creator = "@kytta@fosstodon.org"

# fediring_host = "kytta.dev"

[languages.de]

title = "@kytta"
description = "Ein π-förmiger Webentwickler."
