base_url = "https://www.kytta.dev"

title = "Nikita Karamov"
description = "A Ï€-shaped web developer."
author = "Nikita Karamov"

default_language = "en"

compile_sass = true
minify_html = true
generate_feed = true

build_search_index = true

[markdown]
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
    { theme = "OneHalfDark", filename = "syntax-theme-dark.css" },
    { theme = "OneHalfLight", filename = "syntax-theme-light.css" },
]

external_links_no_follow = true
external_links_no_referrer = true

smart_punctuation = true

[search]
include_title = true
include_description = true
include_content = true

[extra]
