#!/bin/sh

set -eu

# shellcheck disable=SC2046
pnpm exec glyphhanger $(git ls-files --others -- 'public/*.html') \
	--US_ASCII \
	--family="InterDisplay" \
	--subset="$PWD/fonts-src/Inter-DisplayMedium.otf" \
	--formats=woff2 \
	--output="$PWD/static/fonts" \
	--jsdom
