name: Check links

on:
  schedule:
    - cron: "16 13 * * 0"
  repository_dispatch:
  workflow_dispatch:
  pull_request:
    branches:
      - v8

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          submodules: recursive
          lfs: true
      - name: Restore lychee cache
        uses: actions/cache@v3
        with:
          path: .lycheecache
          key: cache-lychee-${{ hashFiles('**/*.md') }}
          restore-keys: cache-lychee-
      - uses: taiki-e/install-action@v2
        with:
          tool: zola@0.17.2

      - run: zola build

      - name: Check links
        id: lychee
        uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose --no-progress './public/**/*.html'
          output: ./lycheeresult.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create issue
        if: ${{ github.event_name != 'pull_request' && env.lychee_exit_code != 0 }}
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: "[lychee] Broken links"
          content-filepath: ./lycheeresult.md
          labels: bug, automated issue
