name: Check links

on:
  schedule:
    - cron: "16 13 * * 0"
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Restore lychee cache
        uses: actions/cache@v4
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-
      - uses: taiki-e/install-action@v2
        with:
          tool: zola@0.19.1

      - run: zola build

      - name: Check links
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress --root-dir "$GITHUB_WORKSPACE/public/" './public/**/*.html'
          output: ./lycheeresult.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create issue
        if: ${{ github.event_name != 'pull_request' && steps.lychee.outputs.exit_code != 0 }}
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: "[lychee] Broken links"
          content-filepath: ./lycheeresult.md
          labels: bug, automated issue
