name: Deploy to GitHub Pages

on:
  push:
    branches:
      - v[0-9]+

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CI_REPO_NAME: codeberg-pages-repo

jobs:
  deploy-v8:
    if: github.ref == 'refs/heads/v8'
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Build
        uses: shalzz/zola-deploy-action@v0.17.0
        env:
          PAGES_BRANCH: gh-pages
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
