name: Deploy preview version

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          lfs: true
      - uses: taiki-e/install-action@v2
        with:
          tool: zola@0.19.1

      - run: zola build --drafts

      - uses: actions/upload-artifact@v4
        with:
          name: preview-${{ github.run_id }}
          path: ./public
          if-no-files-found: error
          retention-days: 1
          overwrite: true
          include-hidden-files: true

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: hynek/setup-cached-uv@v2
      - uses: actions/download-artifact@v4
        with:
          name: preview-${{ github.run_id }}
          path: ./public

      - run: tree
