name: Deploy preview version

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          lfs: true
      - uses: taiki-e/install-action@v2
        with:
          tool: zola@0.19.1

      - run: zola build --drafts

      - uses: actions/upload-artifact@v4
        with:
          name: preview-${{ github.run_id }}
          path: ./public
          if-no-files-found: error
          retention-days: 1
          overwrite: true
          include-hidden-files: true

  deploy:
    runs-on: ubuntu-latest
    environment:
      name: preview
      url: ${{ steps.upload.outputs.url }}
    needs: build
    steps:
      - uses: hynek/setup-cached-uv@v2
      - uses: actions/download-artifact@v4
        with:
          name: preview-${{ github.run_id }}
          path: ./public

      - run: tree

      - id: upload
        run: |
          stdout=$(mktemp)
          uvx smokeshow upload public | tee $stdout
          url=$(tail -n 1 $stdout | awk '{print $3}')
          echo "output_url=$url" >> $GITHUB_OUTPUT
        env:
          SMOKESHOW_AUTH_KEY: ${{ secrets.SMOKESHOW_AUTH_KEY }}
          SMOKESHOW_GITHUB_STATUS_DESCRIPTION: Preview
          SMOKESHOW_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
